apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: {{ template "fullname" . }}-fast
  # name: gitlab-glusterfs
  namespace: default
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.47.0.2:8080"
